apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: mx-bank
build:
  local:
    push: true
  artifacts:
    - image: "{{.IMAGE_NAME}}"
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "services/transaction/**/*.*"
            dest: .
deploy:
  helm:
   releases:
    - name: transaction-service
      chartPath: deploy/k8s/charts/transaction-service
      valuesFiles:
        - deploy/k8s/charts/transaction-service/values/values.dev.yaml
      setValueTemplates:
        image.repository: "{{.IMAGE_NAME}}"
      namespace: transaction-service
      createNamespace: true