apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: mx-bank-service
build:
  local:
    push: false
  artifacts:
    - image: 324654522070.dkr.ecr.us-east-1.amazonaws.com/dev-mx-bank-service-repository
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
deploy:
  helm:
    releases:
    - name: mx-bank-service
      chartPath: deploy/k8s
      valuesFiles:
        - deploy/k8s/values.yaml
      setValueTemplates:
        image.repository: "{{.IMAGE_NAME}}"
      # namespace: mx-bank-service
      createNamespace: true

  # kubectl: { 
  #   defaultNamespace: mx-bank-service 
  #   }
# manifests:
#   rawYaml:
#     - './deploy/k8s/templates/namespace.yml'
#     - './deploy/k8s/templates/peer-authentication.yml'
#     - './deploy/k8s/templates/tx-svc/configmap.yml'
#     - './deploy/k8s/templates/tx-svc/service.yml'
#     - './deploy/k8s/templates/tx-svc/ingress.yml'
#     - './deploy/k8s/templates/tx-svc/secret.yml'
#     - './deploy/k8s/templates/tx-svc/deployment.yml'
#     - './deploy/k8s/templates/db/pvc.yml'
#     - './deploy/k8s/templates/db/configmap.yml'
#     - './deploy/k8s/templates/db/network-policy.yml'
#     - './deploy/k8s/templates/db/deployment.yml'
#     - './deploy/k8s/templates/db/service.yml'
