apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: mx-bank-service
build:
  local:
    push: false
  artifacts:
    - image: 324654522070.dkr.ecr.us-east-1.amazonaws.com/dev-mx-bank-service-repository
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
deploy:
  kubectl: { 
    defaultNamespace: mx-bank-service 
    }

manifests:
  rawYaml:
    - './deploy/k8s/templates/namespace.yml'
    - './deploy/k8s/templates/peer-authentication.yml'
    - './deploy/k8s/templates/app/configmap.yml'
    - './deploy/k8s/templates/app/service.yml'
    - './deploy/k8s/templates/app/ingress.yml'
    - './deploy/k8s/templates/app/secret.yml'
    - './deploy/k8s/templates/app/deployment.yml'
    - './deploy/k8s/templates/db/pvc.yml'
    - './deploy/k8s/templates/db/configmap.yml'
    - './deploy/k8s/templates/db/network-policy.yml'
    - './deploy/k8s/templates/db/deployment.yml'
    - './deploy/k8s/templates/db/service.yml'
