apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: mx-bank-service
build:
  local:
    push: true
  artifacts:
    - image: "{{.IMAGE_NAME}}"
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
deploy:
  helm:
   releases:
    - name: mx-bank-service
      chartPath: deploy/k8s
      valuesFiles:
        - deploy/k8s/values.yaml
      setValueTemplates:
        image.repository: "{{.IMAGE_NAME}}"
      namespace: mx-bank-service
      createNamespace: true