apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: mx-bank-service
build:
  local:
    push: false
  artifacts:
    - image: ksd-mx/mx-bank-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
deploy:
  kubectl: { 
    defaultNamespace: mx-bank-service 
    }

manifests:
  rawYaml:
    - './deploy/k8s/templates/namespace.yml'
    - './deploy/k8s/templates/app/deployment.yml'
    - './deploy/k8s/templates/app/service.yml'
    - './deploy/k8s/templates/app/configmap.yml'
    - './deploy/k8s/templates/app/ingress.yml'

# deploy:
#   helm:
#     releases:
#       - name: mx-bank-service
#         chartPath: deploy/k8s
#         valuesFiles:
#           - deploy/k8s/values.yaml
#         setValues:
#           app.image: ksd-mx/mx-bank-service
#         namespace: mx-bank-service