replicaCount: 3

app:
  image: ksd-mx/mx-bank-service
  containerPort: 9000

db:
  image: postgres:latest
  containerPort: 5432

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: mx-bank-service.local
      paths: []

resources: {}