apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: mx-bank-service
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
  - host: localhost 
    http:
      paths:
      - pathType: Exact
        path: "/"
        backend:
          service:
            name: hello-world-service
            port:
              number: 9000